[tool.poetry]
name = "scprint"
version = "0.1.0"
license = "MIT"
description = ""
authors = ["jeremie kalfon"]
readme = ["README.md", "LICENSE"]
repository = "https://github.com/jkobject/scPrint"
keywords = [
  "scRNAseq",
  "transformer",
  "GRN",
  "gene regulatory network",
  "scPrint",
]

[tool.poetry.dependencies]
lamindb = "*"
python = "3.10"
cellxgene-census = "*"
torch = ">=2.0.0"
anndata = "*"
matplotlib = "*"
seaborn = "*"
gseapy = "*"
ipykernel = "*"
owlready2 = "*"
# torchdata = "*"
biomart = "*"
scib = "*"
scikit-learn = "*"
scipy = "*"
pandas = ">=2.0.0"
numpy = "*"
leidenalg = "*"
decoupler = "*"
Bio = "*"
attridict = "*"
gget = "*"
torchvision = "*"
fair-esm = { git = "https://github.com/facebookresearch/esm.git", branch = "main" }
hydra-core = "*"
lightning = "*"
# torchtext = "*"
transformers = "*"
pynndescent = ">=0.5.11"
scDataLoader = "*"
einops = "*"
rich = "*"
pytorch-fast-transformers = "*"
typeshed-client = "*"
tensorboardX = "*"
jsonargparse = "*"
docstring-parser = "*"
lnschema-bionty = "*"
bionty = "*"
wandb = "*"

[tool.poetry.group.cuda.dependencies]
# C_INCLUDE_PATH=$CONDA_HOME/envs/scprint/include

torchtext = "0.15.0"
triton = "2.0.0.dev20221202"
torch = "2.0.0"
torchvision = "0.15.0"
torchaudio = "2.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
coverage = "^7.3.2"
flake8 = "^6.1.0"
black = "^23.10.1"
isort = "^5.12.0"
pytest-cov = "^4.1.0"
mypy = "^1.6.1"
gitchangelog = "^3.0.4"
mkdocs = "^1.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scprint = 'scprint.__main__:main'
