[tool.poetry]
name = "scprint"
version = "0.1.0"
license = "MIT"
description = ""
authors = ["jeremie kalfon"]
readme = ["README.md", "LICENSE"]
repository = "https://github.com/jkobject/scPrint"
keywords = [
  "scRNAseq",
  "transformer",
  "GRN",
  "gene regulatory network",
  "scPrint",
]

[tool.poetry.dependencies]
python = "3.10"
cellxgene_census = "*"
tiledbsoma = "*"
torch = "*"
anndata = "*"
matplotlib = "*"
seaborn = "*"
gseapy = "*"
ipykernel = "*"
owlready2 = "*"
torchdata = "*"
biomart = "*"
scib = "*"

[tool.poetry.group.cuda.dependencies]


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
coverage = "^7.3.2"
flake8 = "^6.1.0"
black = "^23.10.1"
isort = "^5.12.0"
pytest-cov = "^4.1.0"
mypy = "^1.6.1"
gitchangelog = "^3.0.4"
mkdocs = "^1.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scprint = 'scprint.__main__:main'
