### 1 init

--config config/ablation_study.yml
1892372
kxtm7jtn
9zdkhlej
4ezrufy9
1964988
4ihs8zbj #697jiesc

##### 2 change the weight scaling
data:
  weight_scaler: 3000

--data.weight_scaler 3000
1892510
hzjj21j9
fopg9qt2
ym72b3do
1965013
joyets6s

#### 3 change how many cells per group before changing groups (twice as less)
trainer:
  limit_train_batches: 10000
  reload_dataloaders_every_n_epochs: 5
  max_epochs: 40
scprint_training:
  test_every: 5

--trainer.limit_train_batches 10000 --trainer.reload_dataloaders_every_n_epochs 5 --trainer.max_epochs 40
1899680
f2jxue8p
mh40wxyo
qu8zv48c
1965407
e20jt0en
# check e20jt0en for an issue at 320K

### 4 without replacement

data:
  replacement: False

--data.replacement False
1899260
oj8i38ur
mygjp7yc
ltt10c1r
1965675
qw48w6p6

#### 5 only scale on cell groups:
data:
  clss_to_weight:
    - clust_cell_type

--data.clss_to_weight '[\"clust_cell_type\"]'
1890999
h9mvhutk
fvp021zs
1968280
konhvgyn

### 6 only scale on nnz:
data:
  clss_to_weight:
    - nnz
    - clust_cell_type
  weight_scaler: 500

--data.clss_to_weight [\"nnz\"\,\"clust_cell_type\"] --data.weight_scaler 500"
1899455
jmhazi02
sftebnir
lvqytack
1968336
6i2xs1cf

### 7 same but just changing the seed

--seed_everything 52
1892748
vl9a2ts7
5n582rb8
lf40wfq0

#### 8 do just some humans
data:
  collection_name: scPRINT-V2 (100 random humans)
  organisms:
    - NCBITaxon:9606

--data.collection_name \"scPRINT-V2 (100 random humans)\" --data.organisms '[\"NCBITaxon:9606\"]'
1900679
jqzb61j3
1x19dtk2
ok9jk2b5

#### 9 do just good quality
data:
  collection_name: scPRINT-V2 (good quality)

--data.collection_name \"scPRINT-V2 (good quality)\"
1899738
rrv1nn8j
5w46eeyv
lxgx7fm1

#### 10 change how many cells per group before changing groups (twice as less)
trainer:
  limit_train_batches: 5000
  reload_dataloaders_every_n_epochs: 3
  max_epochs: 80
scprint_training:
  test_every: 5
data:
  weight_scaler: 20
  replacement: False

--trainer.limit_train_batches 5000 --trainer.reload_dataloaders_every_n_epochs 3 --trainer.max_epochs 80 --scprint_training.test_every 5 --data.weight_scaler 20 --data.replacement False
1926500
36za6yxt

#### 10 change how many cells per group before changing groups (twice as less)
trainer:
  limit_train_batches: 20000
  reload_dataloaders_every_n_epochs: 2
  max_epochs: 60
scprint_training:
  test_every: 5
data:
  weight_scaler: 20
  replacement: False
  train_oversampling_per_epoch: 0.2

#### 11 all (already done)

#### 12 old (already done)

##### 13 untrained model’s performance
trainer:
  limit_train_batches: 1
  limit_val_batches: 200
  limit_test_batches: 1 # we don't perform tests this way
  max_epochs: 2
scprint_training:
  test_every: 1

--trainer.limit_train_batches 1 --trainer.limit_val_batches 2 --trainer.limit_test_batches 1 --trainer.max_epochs 2 --scprint_training.test_every 1
1927023
udjxr8q1

###### 14 noise
scprint_training:
  noise: [0.6]
  do_denoise: True
  mask_ratio: []

--scprint_training.noise [0.6] --scprint_training.do_denoise True --scprint_training.mask_ratio []
1955892

###### 15 mask and generate
scprint_training:
  mask_ratio: [\"TF\"]

--scprint_training.mask_ratio ['TF']
1955923

###### 16 noise, full forward, mask, cce
scprint_training:
  run_full_forward: True
  noise: [0.6]
  do_denoise: True
  do_cce: True
  mask_ratio: [\"TF\"]

--scprint_training.mask_ratio ['TF'] --scprint_training.do_cce True --scprint_training.noise [0.6] --scprint_training.do_denoise True --scprint_training.run_full_forward True
1955977

#### 17 without class embd diss scale:
scprint_training:
  class_embd_diss_scale: 0

--scprint_training.class_embd_diss_scale 0
1956021

###### 18 no generate
scprint_training:
  do_generate: False

--scprint_training.do_generate False
1956026

##### 9 ECS
scprint_training:
  do_ecs: True

--scprint_training.ecs True

##### 19 no zinb vs mse vs both
scprint_training: 
  zinb_and_mse: True
  do_denoise: True
  noise: [0.6]
  mask_ratio: []

--scprint_training.zinb_and_mse True --scprint_training.noise [0.6] --scprint_training.do_denoise True --scprint_training.mask_ratio []

#### 21 do mvc instead of generate
scprint_training:
  do_mvc: True

--scprint_training.do_mvc True

##### 33 Test multi context vs fixed
scprint_training:
  var_context_length: True
data:
  max_len: 3200

--data.max_len 3200 --scprint_training.var_context_length True

##### 24 change gene position tolerence
data:
  gene_position_tolerance: 1000

--data.gene_position_tolerance 1000

##### 25 don't do gene pos
data:
  do_gene_pos: False

--data.do_gene_pos False

### 29 versus only scale on cells
data:
  clss_to_weight:
    - cell_type_ontology_term_id

--data.clss_to_weight ['cell_type_ontology_term_id']

### 30 add scale on nnz
data:
  clss_to_weight:
    - clust_cell_type
    - tissue_ontology_term_id
    - disease_ontology_term_id
    - age_group
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    - nnz

###### 34 test metacells
data:
  metacell_mode: 0.2

--data.metacell_mode 0.2

##### 13 Test attention bias faded vs none (MAKE SURE RIGHT DIR (T))
model:
  attn_bias: full

--model.attn_bias full

##### 14 no dropout
model:
  dropout: 0

--model.dropout 0

##### 15 do cell specific blocks
model:
  cell_specific_blocks: True

--model.cell_specific_blocks True

##### 16 learn gene embeddings
model:
  freeze_embeddings: False

--model.freeze_embeddings False
  
##### 17 norm sum
model:
  normalization: sum

--model.normlization sum

##### 18 no zinb vs mse vs both
model:
  zinb: False

--model.zinb False

#### 20 do depth at input
model:
  depth_atinput: True

--model.depth_atinput True

34*100 = 3400 H100 GPU
##### Test cheap vs esm2 vs learnt