project: scprint_v2
seed_everything: 42
set_float32_matmul_precision: True
trainer:
  precision: 16-mixed
  strategy: ddp_find_unused_parameters_true
  use_distributed_sampler: False
  gradient_clip_val: 3
  log_every_n_steps: 100
  limit_train_batches: 40000
  gradient_clip_algorithm: norm
  limit_val_batches: 10000
  limit_test_batches: 1 # we don't perform tests this way
  accumulate_grad_batches: 1
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: ${project}
        save_dir: /lustre/fswork/projects/rech/xeg/uat95fg/ #/pasteur/zeus/projets/p02/ml4ig_hot/Users/jkalfon/ #/data/log/
        offline: True
  callbacks:
    #- class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
    #  init_args:
    #    swa_lrs: 0.03
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        save_top_k: 10
        save_last: True
scprint_training:
  run_full_forward: True
  noise: [0.7]
  do_ecs: True
  do_cce: True
  zinb_and_mse: True
  var_context_length: True
scprint_early_stopping:
  patience: 4
model:
  dropout: 0.1
  num_heads_kv: 4
  transformer: flash
  residual_in_fp32: True
  checkpointing: True
  cell_specific_blocks: True
  fused_dropout_add_ln: False
  depth_atinput: False
  fused_mlp: False
  fused_bias_fc: False
  drop_path_rate: 0
  class_compression: vae
  freeze_embeddings: True
  finetune_gene_emb: True
  normalization: log
  class_compression: vae
  pred_embedding:
    - cell_type_ontology_term_id
  #compress_class_dim:
  #  cell_type_ontology_term_id: 18 # 20
  #  tissue_ontology_term_id: 8
  #  disease_ontology_term_id: 14
  #  age_group: 8
  #  assay_ontology_term_id: 5 #6
  #  self_reported_ethnicity_ontology_term_id: 10
  #  sex_ontology_term_id: 2
  #  organism_ontology_term_id: 8
  compress_class_dim:
    cell_type_ontology_term_id: 64
    tissue_ontology_term_id: 32
    disease_ontology_term_id: 16
    age_group: 8
    assay_ontology_term_id: 8
    self_reported_ethnicity_ontology_term_id: 8
    sex_ontology_term_id: 2
    organism_ontology_term_id: 8
    cell_culture: 2
    # total: 148
data:
  gene_position_tolerance: 10_000
  gene_embeddings: ./data/main/gene_embs/
  collection_name: scPRINT-V2 (all+tahoe+scbase) #scPRINT-V2 (good quality) # scPRINT-V2 (some)
  how: random expr
  max_len: 2600
  pin_memory: True
  persistent_workers: True
  prefetch_factor: 3
  metacell_mode: 0.2
  weight_scaler: 200
  do_gene_pos: False
  add_zero_genes: 0
  n_samples_per_epoch: 1300000 # {data.batch_size*trainer.limit_train_batches}
  validation_split: 0.05
  test_split: 0.02
  batch_size: 32
  num_workers: 5
  hierarchical_clss:
    - cell_type_ontology_term_id
    - tissue_ontology_term_id
    - disease_ontology_term_id
    - age_group
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
  clss_to_weight:
    - clust_cell_type
    - tissue_ontology_term_id
    - disease_ontology_term_id
    - age_group
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    - cell_culture
    - nnz
  clss_to_predict:
    - cell_type_ontology_term_id
    - tissue_ontology_term_id
    - disease_ontology_term_id
    - age_group
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    - cell_culture
