trainer:
  max_time:
    hours: 2
  logger: []
  limit_predict_batches: 5000 
  strategy: auto
  num_sanity_val_steps: 0
  default_root_dir: /pasteur/zeus/projets/p02/ml4ig_hot/Users/jkalfon/predict/
data:
  collection_name: all no zhang13M #preprocessed dataset #
  max_len: 2200
  add_zero_genes: 0
  batch_size: 64
  num_workers: 12
  organisms:
    - NCBITaxon:9606
    - NCBITaxon:10090
  gene_position_tolerance: 10_000
  gene_embeddings: ./data/main/gene_embeddings.parquet
  how: random expr
  weight_scaler: 20
  do_gene_pos: ./data/main/biomart_pos.parquet
  train_oversampling_per_epoch: 0.4
  validation_split: 0.02
  test_split: 0.02
  # TODO: drop tissue & dev stage until part or is taken in account
  hierarchical_clss:
    - cell_type_ontology_term_id
    #- tissue_ontology_term_id
    - disease_ontology_term_id
    #- development_stage_ontology_term_id
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
  clss_to_weight:
    - cell_type_ontology_term_id
    # - tissue_ontology_term_id
    - disease_ontology_term_id
    # - development_stage_ontology_term_id
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    # - cell_culture
  clss_to_pred: ${data.clss_to_weight}
  all_clss:
    - cell_type_ontology_term_id
    # - tissue_ontology_term_id
    - disease_ontology_term_id
    # - development_stage_ontology_term_id
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    #- heat_diff
    #- total_counts
    #- nnz
    #- dpt_group
    #- dataset_id
    #- cell_culture