project: scprint_test
seed_everything: 42
ckpt_path: null
set_float32_matmul_precision: True
trainer:
  precision: 16
  profiler: simple
  gradient_clip_val: 10
  reload_dataloaders_every_n_epochs: 1
  max_time:
    hours: 1
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: ${project}
        save_dir: ./data/logs/
  callbacks:
    - class_path: scprint.trainer.TrainingMode
      init_args:
        do_denoise: True
        noise:
          - 0.3
        do_cce: True
        cce_sim: 0.5
        do_ecs: True
        ecs_threshold: 0.3
        ecs_scale: 1.0
        do_mvc: False
        do_adv_cls: False
        do_next_tp: False
        class_scale: 1000.0
        mask_ratio:
          - 0.15
          - 0.3
    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 0.01
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        save_top_k: -1
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 10
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: scprint.cli.MySaveConfig
      init_args:
        wandblog: all
        log_freq: 400
        log_graph: True
model:
  nhead: 4
  nlayers: 4
  layers_cls: [128]
  dropout: 0.2
  transformer: flash
  mvc_decoder: inner product
  d_model: 128
  d_hid: 128
  residual_in_fp32: True
  num_heads_kv: null
  fused_dropout_add_ln: False
  return_residual: False
  prenorm: True
  fused_mlp: False
  fused_bias_fc: False
  drop_path_rate: 0.02
  pred_embedding:
    - cell_type_ontology_term_id
    - disease_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
data:
  organisms:
    - NCBITaxon:9606
  gene_position_tolerance: 10_000
  gene_embeddings: ./data/temp/embeddings.parquet
  collection_name: preprocessed dataset
  how: most expr
  max_len: 1000
  add_zero_genes: 100
  train_oversampling: 1.7
  validation_split: 0.2
  test_split: 0.0
  batch_size: 64
  num_workers: 8
  # TODO: drop tissue & dev stage until part or is taken in account
  hierarchical_labels:
    - cell_type_ontology_term_id
    # "tissue_ontology_term_id",
    - disease_ontology_term_id
    # "development_stage_ontology_term_id",
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
  label_to_weight:
    - cell_type_ontology_term_id
    # "tissue_ontology_term_id",
    - disease_ontology_term_id
    # "development_stage_ontology_term_id",
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
  label_to_pred: ${data.label_to_weight}
  all_labels:
    - cell_type_ontology_term_id
    # "tissue_ontology_term_id",
    - disease_ontology_term_id
    # "development_stage_ontology_term_id",
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    - heat_diff
    - total_counts
    - nnz
    - dpt_group
    #'dataset_id',
    #'cell_culture',
