trainer:
  strategy: ddp_find_unused_parameters_true
  gradient_clip_val: 2
model:
  nhead: 32
  num_heads_kv: 8
  nlayers: 30
  d_model: 2048
  d_model_cell: 512
  nhead_cell: 8
  nlayers_cell: 10
  checkpointing: True
data:
  batch_size: 1
  max_len: 2400
  n_samples_per_epoch: 40000
scprint_training:
  run_full_forward: False
