model:
  nhead: 32
  num_heads_kv: 8
  nlayers: 30
  layers_cls: []
  d_model: 2048
  d_model_cell: 512
  nhead_cell: 8
  nlayers_cell: 10
  checkpointing: True
data:
  batch_size: 1
  max_len: 2200
  n_samples_per_epoch: 40000
scprint_training:
  run_full_forward: False
  noise: [0.7]
  do_ecs: True
  do_cce: True
  mask_ratio: ["TF"]