trainer:
  strategy: ddp_find_unused_parameters_true
  # num_nodes: 2
  log_every_n_steps: 100
  limit_train_batches: 5000
  limit_val_batches: 16000
  reload_dataloaders_every_n_epochs: 1
  accumulate_grad_batches: 1
  callbacks:
    - class_path: scprint.trainer.TrainingMode
      init_args:
        do_denoise: True
        noise: 
          - 0.3
        do_cls: True
        class_scale: 2
        warmup_duration: 1000
model:
  lr: 0.0001
  optim: "adamW"
  weight_decay: 0.02
  nhead: 20
  nlayers: 32
  layers_cls: [512]
  d_model: 1280
data:
  collection_name: preprocessed dataset #all no zhang13M
  how: random expr
  max_len: 2400
  weight_scaler: 10
  train_oversampling_per_epoch: 0.4
  batch_size: 8
  num_workers: 12