trainer:
  strategy: ddp_find_unused_parameters_true
model:
  nhead: 8
  num_heads_kv: 4
  nlayers: 16 #used to be 12
  layers_cls: [256]
  d_model: 512
  dropout: 0.1
data:
  batch_size: 16
  n_samples_per_epoch: 1_000_000

