trainer:
  strategy: ddp_find_unused_parameters_true
  num_nodes: 3
  log_every_n_steps: 100
  limit_train_batches: 7000
  limit_val_batches: 1000
  reload_dataloaders_every_n_epochs: 1
  accumulate_grad_batches: 1
  callbacks:
    - class_path: scprint.trainer.TrainingMode
      init_args:
        do_denoise: True
        noise: 
          - 0.3
        do_cce: False
        do_ecs: False
        do_mvc: False
        do_generate: True
        do_adv_cls: False
        do_next_tp: False
        do_adv_batch: False
        run_full_forward: False
        do_cls: True
        class_scale: 1.5
        warmup_duration: 1500
        fused_adam: True
        lr_reduce_factor: .66
        lr_reduce_patience: 2
        mask_ratio: []
model:
  lr: 0.0001
  optim: "adamW"
  weight_decay: 0.04
  nhead: 20
  nlayers: 32
  layers_cls: [512]
  d_model: 1280
  freeze_embeddings: False
data:
  collection_name: all no zhang13M #preprocessed dataset #all no zhang13M
  how: random expr
  max_len: 2200
  weight_scaler: 40
  train_oversampling_per_epoch: 0.05
  batch_size: 3
  num_workers: 6