trainer:
  precision: 16-mixed
  gradient_clip_val: 500
  strategy: ddp_find_unused_parameters_true
  callbacks:
    - class_path: scprint.trainer.TrainingMode
      init_args:
        do_denoise: True
        noise: 
          - 0.3
        do_cce: False
        do_ecs: False
        do_mvc: False
        do_generate: True
        do_adv_cls: False
        do_next_tp: False
        do_adv_batch: False
        run_full_forward: False
        do_cls: True
        class_scale: 1.5
        warmup_duration: 500
        fused_adam: True
        lr_reduce_factor: .66
        lr_reduce_patience: 2
        mask_ratio: []
    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 0.03
model:
  lr: 0.0001
  optim: "adamW"
  weight_decay: 0.02
  nhead: 8
  nlayers: 16 #used to be 12
  layers_cls: [512]
  d_model: 512
  freeze_embeddings: False
data:
  max_len: 2200
  weight_scaler: 40
  train_oversampling_per_epoch: 0.4
  batch_size: 16
  num_workers: 12
