trainer:
  strategy: ddp_find_unused_parameters_true
  gradient_clip_val: 2
model:
  nhead: 16
  num_heads_kv: 4
  lr: 0.00005
  nlayers: 30
  d_model: 1024
data:
  batch_size: 4
  num_workers: 10
  max_len: 2400
