model:
  nhead: 24
  num_heads_kv: 6
  nlayers: 33
  layers_cls: []
  d_model: 1536
  checkpointing: True
data:
  batch_size: 1
  prefetch_factor: 16
  num_workers: 10
  max_len: 2200
  n_samples_per_epoch: 40000
scprint_training:
  run_full_forward: False
  noise: [0.7]
  do_ecs: True
  do_cce: True
  mask_ratio: ["TF"]